name: Build and Release

on:
  push:
    tags:
      - 'v*.*'
    branches:
      - actions-test
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download w3string encoder
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri '${{ secrets.ENCODER_URI }}' -OutFile '${{ github.workspace }}\w3strings.exe'

    - name: Run build script
      shell: pwsh
      run: |
        New-Alias -Name w3strings -Value ${{ github.workspace }}\w3strings
        .\build.ps1 -idFixedPart 9990

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: BetterRumbleSupport.zip
        path: build/

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: BetterRumbleSupport.zip
        path: build/

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: build/*.zip